services:
  app:
    build:
      dockerfile: Dockerfile
    image: sandbox-python-fastapi
    tty: true
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox_user
      POSTGRES_PASSWORD: sandbox_user

volumes:
  pgdata:
